[tool.poetry]
name = "rethinking"
version = "0.1.0"
description = "Statistical Rethinking"
authors = ["Ludovic Tiako <ludovic.tiako@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
# arviz = "^0.12.0" # https://github.com/python-poetry/poetry/issues/3219
funsor = "^0.4.3"
jupyter = "^1.0.0"
numpyro = "^0.9.1"
plotly = "^5.6.0"
jupyter-contrib-nbextensions = "^0.5.1"
black = "^22.1.0"
nb-black = "^1.0.7"
isort = "^5.10.1"
pandas = "^1.4.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
